sudo: false
language: php
php:
  - 7.0

matrix:
  fast_finish: true

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - vendor

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - nvm install --lts

script:
  - composer install -o --prefer-dist --no-interaction
